theme: jekyll-theme-minimal
title: Versioning Wordsworth's "Nutting" from Manuscript to Modern Publication
description: A digital edition made by Taylor Brown for Paul Eggert's ENGL 413 class at Loyola University Chicago, Spring 2018. 
